language: c++
branches :
  only:
  - arduino
sudo: false
before_install:
  - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
install:
  - arduino --install-library "Adafruit SleepyDog Library,Adafruit FONA Library"
script:
  - build_main_platforms
notifications:
  slack: kealingalgebra2:MyCH2sHZL1y591A2OdPEr8At
