#This is a comment, you use the hashtag to start a comment.

#Put the files you want to check in arduino/source.

#Put any dependencies libraries in arduino/refs.

language: $COMPILE_LANG
python:
    - "2.7"
env:
    - COMPILE_LANG=python
    - COMPILE_LANG=cpp

# Cache PlatformIO packages using Travis CI container-based infrastructure
cache:
    directories:
        - "~/.platformio"

install:
    - pip install --upgrade pip
    - pip install -U platformio
    - pip install -U -r python/refs/requirements.txt
script:
    - source scripts/build_arduino.sh
    - 
    - #pytest python/source/ FIXME
    
notifications:
    slack: kealingalgebra2:MyCH2sHZL1y591A2OdPEr8At
