#This is a comment, you use the hashtag to start a comment.

#Put the files you want to check in arduino/source.

#Put any dependencies libraries in arduino/refs.

language: python

sudo: required

python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
cache:
    directories:
        - "~/.platformio"

install:
    - sudo pip install --upgrade pip
    - pip install -U platformio
    - pip install -U -r python/refs/requirements.txt
    - #pip install -U opencv-python
script:
    - source scripts/build_arduino.sh
    - 
    - #./configure && make && make test
    - #ls ./configure
    - #ls ./
    - #pytest python/source/ FIXME
    
notifications:
    slack: kealingalgebra2:MyCH2sHZL1y591A2OdPEr8At
