#This is a comment, you use the hashtag to start a comment.

#Put the files you want to check in arduino folder.

#Put any dependencies libraries in arduino/refs.

language: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
cache:
    directories:
        - "~/.platformio"
        
env:
    - PATH=scripts/

install:
    - pip install -U platformio
    
    - unzip arduino/refs/\*.zip -d libs/

script:
    - build_arduino.sh
notifications:
    slack: kealingalgebra2:MyCH2sHZL1y591A2OdPEr8At
