#This is a comment, you use the hashtag to start a comment.

language: $COMPILE_LANG
python:
    - "2.7"
env:
    - COMPILE_LANG=python
    - COMPILE_LANG=arduino

# Cache PlatformIO packages using Travis CI container-based infrastructure
cache:
    directories:
        - "~/.platformio"

install:
#Install pip locally, allows for upgrade without sudo requirement
    - wget https://bootstrap.pypa.io/get-pip.py && python get-pip.py --user
    - ls /usr/local/bin

script:
    - source "scripts/build_$COMPILE_LANG.sh"
    
notifications:
    slack: kealingalgebra2:MyCH2sHZL1y591A2OdPEr8At
