#This is a comment, you use the hashtag to start a comment.

#Put the files you want to check in env: I have a sample inside for now.

#Put any dependencies libraries in refs.

#You can have multiple code files and dependencies.

language: python
python:
    - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=arduino/\*.ino

install:
    - pip install -U platformio
    
    - unzip arduino/refs/\*.zip -d /tmp/

script:
    - platformio ci --lib="/tmp/Adafruit_NeoPixel-master" --board=uno
notifications:
    slack: kealingalgebra2:MyCH2sHZL1y591A2OdPEr8At
